name: Run Preprocessing Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Tetap menggunakan versi 3.12 sesuai aturan submisi Anda
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' 

    # Perbaikan khusus Python 3.12: setuptools harus diinstal duluan di baris terpisah
    - name: Install Dependencies Directly
      run: |
        python -m pip install --upgrade pip
        pip install "setuptools<70.0.0"
        pip install numpy pandas matplotlib seaborn scikit-learn plotly yellowbrick kagglehub

    - name: Run Preprocessing Script
      run: python preprocessing/automate_Srie_Wahyudhanis_Hadis.py

    - name: Commit and Push Preprocessed Data
      run: |
        git config --global user.name "ririhadis"
        git config --global user.email "sriewahyudhanis.hadis@gmail.com"
        
        if [ -f data_preprocessing.csv ]; then
          git add data_preprocessing.csv
          git commit -m "Automated update: data_preprocessing.csv [skip ci]" || echo "Tidak ada perubahan data baru"
          git push origin main
        else
          echo "Eror: File data_preprocessing.csv gagal dibuat oleh skrip!"
          exit 1
        fi
